---

- hosts: all
  become: yes
  tasks:
    - name: install remote URL and archives for disjoint grid
      command: 'psconfig remote  add --configure-archives "http://md.ufixu.com/psconfig/ps-disj.json"'
      
    - name: restart psconfig-pscheduler-agent
      service:
        name: psconfig-pscheduler-agent
        state: restarted
