---

- hosts: all
  become: yes
  tasks:
    - name: Copy a new "sudoers" file into place, after passing validation with visudo
      copy:
        src: /home/vagrant/perfSONAR-Sample/ps-disj.json
        dest: /vagrant
     
    - name: publish .json file
      command:  "psconfig publish /vagrant/ps-disj.json"

    - name: make availalbe to nodes psconfig remote
      command:  'psconfig remote add "http://md.ufixu.com/psconfig/ps-disj.json"'

    - name: restart psconfig-maddash-agent
      service:
        name: psconfig-maddash-agent
        state: restarted

    - name: restart httpd
      service:
        name: httpd
        state: restarted
