---

- hosts: all
  become: yes
  tasks:
    - name: copy disjoint.json file to Maddash node
      copy:
        src: ../perfS-json-files/disjoint.json
        dest: /home/vagrant/disjoint.json
        owner: vagrant
        group: vagrant
     
    - name: publish disjoint.json file
      command:  "psconfig publish /home/vagrant/disjoint.json"

    - name: make availalbe to nodes
      command:  'psconfig remote add "http://md.ufixu.com/psconfig/disjoint.json"'

    - name: restart psconfig-maddash-agent
      service:
        name: psconfig-maddash-agent
        state: restarted

    - name: restart httpd
      service:
        name: httpd
        state: restarted
