---

- hosts: all
  become: yes
  tasks:
    - name: install EPEL an perfsonar repos
      yum:
        name:
          - epel-release
          - http://software.internet2.edu/rpms/el7/x86_64/latest/packages/perfSONAR-repo-0.10-1.noarch.rpm
        state: present

    - name: add perfsonar-centralmanagment rpm
      yum:
        name:
          - perfsonar-centralmanagement
          - htop
        state: present

    - name: copy mesh.json file to Maddash node
      copy:
        src: ../perfS-json-files/mesh.json
        dest: /home/vagrant/mesh.json
        owner: vagrant
        group: vagrant
     
    - name: Publish .json file
      command:  "psconfig publish /home/vagrant/mesh.json"

    - name: Remote add file
      command:  'psconfig remote add "http://md.ufixu.com/psconfig/mesh.json"'

    - name: start FW service if not running
      service:
        name: firewalld
        state: started

    - name: enable FW service
      service:
        name: firewalld
        enabled: yes

    - name: add http to firewall
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled

    - name: add https to firewall
      firewalld:
        service: https
        permanent: yes
        immediate: yes
        state: enabled

    - name: add esmond access for local net
      command:  "/usr/sbin/esmond_manage add_user_ip_address example-user1 192.168.1.0/24"

    - name: add new project name for web site
      ansible.builtin.replace:
        path: /etc/maddash/maddash-webui/config.json
        regexp: '"My perfSONAR Dashboard"'
        replace: '"Example Maddash setup, with disjoint option"'

    - name: add correct grid name, so it opens first
      ansible.builtin.replace:
        path: /etc/maddash/maddash-webui/config.json
        regexp: '"My Sites"'
        replace: '"1 PSproj"'

    - name: enable cassandra
      service:
        name: cassandra
        enabled: yes

    - name: start cassandra
      service:
        name: cassandra
        state: started

    - name: restart maddash-server
      service:
        name: maddash-server
        state: restarted

    - name: restart psconfig-maddash-agent
      service:
        name: psconfig-maddash-agent
        state: restarted

    - name: restart httpd
      service:
        name: httpd
        state: restarted

    - name: shorten test times, packet loss, every 5min
      command:  "psconfig maddash-grid edit --name default_loss --check-interval PT5M"

    - name: shorten test time, throughput, every 2hr
      command: "psconfig maddash-grid edit --name default_throughput --check-interval PT2H"

