---

- hosts: md
  gather_facts: False
  become: yes
  tasks:
    - name: For med VM, publish disjoint.json file for web use
      command:  "psconfig publish /home/vagrant/disjoint.json"

    - name: For md VM, remote add disjoint file, lets the archive know where the JSON config file lives
      command:  'psconfig remote add "http://192.168.1.213/psconfig/disjoint.json"'

    - name: For md VM, restart psconfig-maddash-agent
      service:
        name: psconfig-maddash-agent
        state: restarted

    - name: For md VM, restart httpd
      service:
        name: httpd
        state: restarted

- hosts: ps,dj
  gather_facts: False
  become: yes
  tasks:
    - name: For ps & dj VMs, install remote URL and archives for disjoint grid
      command: 'psconfig remote  add --configure-archives "http://192.168.1.213/psconfig/disjoint.json"'
      
    - name: For ps & dj VMs, restart psconfig-pscheduler-agent
      service:
        name: psconfig-pscheduler-agent
        state: restarted
