---

- hosts: mad
  become: yes
  tasks:
    - name: Publish disjoint.json file for web use
      command:  "psconfig publish /home/vagrant/disjoint.json"

    - name: Remote add disjoint file, lets the archive know where the JSON config file lives
      command:  'psconfig remote add "http://192.168.1.213/psconfig/disjoint.json"'

    - name: Restart psconfig-maddash-agent
      service:
        name: psconfig-maddash-agent
        state: restarted

    - name: Restart httpd
      service:
        name: httpd
        state: restarted

- hosts: ps,dj
  become: yes
  tasks:
    - name: install remote URL and archives for disjoint grid
      command: 'psconfig remote  add --configure-archives "http://192.168.1.213/psconfig/disjoint.json"'
      
    - name: restart psconfig-pscheduler-agent
      service:
        name: psconfig-pscheduler-agent
        state: restarted
