---

- hosts: all
  become: yes
  tasks:
    - name: install remote URL and archives
      command: 'psconfig remote  add --configure-archives "http://192.168.1.213/psconfig/mesh.json"'
     
    - name: restart psconfig-pscheduler-agent
      service:
        name: psconfig-pscheduler-agent
        state: restarted
