---

- hosts: all
  become: yes
  tasks:
    - name: Copy a new "sudoers" file into place, after passing validation with visudo
      copy:
        src: /home/vagrant/perfSONAR-Sample/ps-proj.json
        dest: /vagrant
     
    - name: install remote URL and archives
      command: 'psconfig remote  add --configure-archives "http://md.ufixu.com/psconfig/ps-proj.json"'
     
    - name: restart psconfig-pscheduler-agent
      service:
        name: psconfig-pscheduler-agent
        state: restarted
