---

- hosts: all
  become: yes
  tasks:
    - name: copy .json file
      command:  "psconfig publish /vagrant/ps-disj.json"

    - name: copy psconfig remote
      command:  'psconfig remote add "http://md.ufixu.com/psconfig/ps-disj.json"'

    - name: restart psconfig-maddash-agent
      service:
        name: psconfig-maddash-agent
        state: restarted

    - name: restart httpd
      service:
        name: httpd
        state: restarted

#    - name: shorten test times, packet loss
#      command:  "psconfig maddash-grid edit --name default_loss --check-interval PT5M"
#
#    - name: shorten test time, throughput
#      command: "psconfig maddash-grid edit --name default_throughput --check-interval PT2H"
