---

- hosts: all
  become: yes
  tasks:
    - name: install extra repos
      yum:
        name:
          - epel-release
          - http://software.internet2.edu/rpms/el7/x86_64/latest/packages/perfSONAR-repo-0.10-1.noarch.rpm
        state: present

    - name: upgrade all packages, excluding kernel related packages
      yum:
        name:
          - perfsonar-testpoint
          - perfsonar-toolkit-security
          - perfsonar-toolkit-servicewatcher
          - perfsonar-toolkit-systemenv-testpoint
          - chrony
          - htop
          - nscd
        state: present

    - name: install remote URL and archives
      command: 'psconfig remote  add --configure-archives "http://md.ufixu.com/psconfig/vmproj.json"'
      
